version: '3'
services:
  kb_back:
    container_name: kb_back
    image: logotipiwe/kb_back:2
    environment:
      DB_HOST: ms
      DB_NAME: keepbalance
      DB_LOGIN: root
      DB_PASS: 1234
    expose:
      - 80
    networks:
      - dc-net
networks:
  dc-net:
    external: true