version: '3'
services:
  kb_back:
    container_name: kb_back
    image: ${KB_BACK_TAG}
    environment:
      DB_HOST: ms
      DB_NAME: keepbalance
      DB_LOGIN: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 80
    networks:
      - dc-net
networks:
  dc-net:
    external: true