version: '3'
services:
  kb_back:
    container_name: kb_back
    image: ${KB_BACK_TAG}
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: keepbalance
      DB_LOGIN: ${DB_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}

      KB_BACK_DEBUG: false
      KB_BACK_DISPLAY_ERR: false
      KB_BACK_AUTO_LOGIN: false
    expose:
      - 80
    networks:
      - dc-net
networks:
  dc-net:
    external: true