version: '3'
services:
  kb_back:
    container_name: kb_back
    image: ${KB_BACK_TAG}
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: keepbalance
      DB_LOGIN: ${DB_LOGIN}
      DB_PASS: ${DB_PASS}
    expose:
      - 80
    networks:
      - dc-net
networks:
  dc-net:
    external: true