name: KB back CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_vars
          token: ${{secrets.PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - uses: actions/checkout@v3
      - name: RUN
        run: |
          echo ${DOCKER_USER}
          echo ${DOCKER_PAT}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PAT }}
      - name: Build&push
        run: |
          export timestamp=$(date +%s)
          export KB_BACK_TAG=${{ env.DOCKER_USER }}/kb_back:time-${timestamp}

          docker build . --tag=${KB_BACK_TAG} --no-cache
          docker push ${KB_BACK_TAG}
  deploy:
    runs-on: ubuntu-latest
    needs: buildAndPush
    steps:
      - name: RUN
        run: |
          echo TAG $KB_BACK_TAG
          echo Docker user ${{env.DOCKER_USER}}