name: KB test
on:
  push:
    branches: [ "test" ]
  workflow_dispatch:
jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - name: RUN
        run: |
          echo ${DOCKER_USER}
          echo ${DOCKER_PAT}
          export tts=ttss
    outputs:
      T0: aaaa
      T1: ${tts}
      T2: ${{env.tts}}
      T3: ${{env.tts}}
  get:
    runs-on: ubuntu-latest
    needs: ["set"]
    steps:
      - name: RUN
        run: |
          echo ${{env.T0}}
          echo ${T0}
          echo ${{needs.set.outputs.T0}}